---
- name: Install data based on OS
  include: "{{ansible_os_family|lower}}_install.yml"
  become: true
  tags: ['rundeck_install']


- name: Deploy rundeck configuration file
  vars:
        dict: "{{rundeck}}"
  template: 
        src: "{{item.key}}.j2"
        dest: "/etc/rundeck/{{item.key}}"
        owner: 'rundeck'
        group: 'rundeck'
        mode: 0640
  with_dict: "{{rundeck}}"
  notify: restart rundeckd
  tags: ['rundeck_config']

- name: Add JDBC Driver
  copy: 
        src: 'oracle/ojdbc14.jar' 
        dest: '/var/lib/rundeck/libext/ojbdc14.jar'
        owner: 'rundeck'
        group: 'rundeck'
        mode: 0644
  when: rundeck['rundeck-config.properties'].datasource.url | search('jdbc:oracle')
  notify: restart rundeckd
  tags: ['rundeck_base_config']

- name: Include node configuration tasks
  include: rundeck_configure_nodes.yml
  tags: ['rundeck_nodes']

